var apiTime,_offSet=
12600
,_location="
london
",userOffset=0,crownOut=!1;const weekdays=["SUNDAY","MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY"];async function getUTC(){await fetch("
https://worldtimeapi.org/api/timezone/Etc/UTC
").then((response=>response.json())).then((data=>{apiTime=data.unixtime}))}const hourHand=document.getElementById("houru"),minHand=document.getElementById("minu"),secHand=document.getElementById("secondu"),dayText=document.getElementById("dayu"),dateText=document.getElementById("dateu"),weatherIcon=document.getElementById("w-icon"),weatherCity=document.getElementById("w-city"),weatherTemp=document.getElementById("w-temp");async function getWeather(){fetch("
https://watchenzonbase.vercel.app/api/currentweather?city=
"+_location).then((resp=>resp.json())).then((w=>{w.ok?(weatherIcon.setAttribute("href","https:"+w.data.current.condition.icon),weatherCity.innerHTML=w.data.location.name,weatherTemp.innerHTML=w.data.current.temp_c+"°C/"+w.data.current.temp_f+"°F"):console.log(w.msg)})).catch(console.error)}const crown=document.getElementById("crown");function actual(){if(crownOut)return;const d=function(dt){return new Date(dt.getTime()+6e4*dt.getTimezoneOffset()+userOffset)}(function(){var userNow=new Date;userOffset=Math.floor(userNow.getTime())-1e3*apiTime;var dt=new Date(0);return dt.setUTCSeconds(apiTime+_offSet),dt}());!function(d){var angleSecond=6*d.getSeconds()+6*d.getMilliseconds()/1e3,angleMin=6*d.getMinutes()+.1*d.getSeconds(),angleHour=30*d.getHours()+.5*d.getMinutes();minHand.setAttribute("transform",`rotate(${angleMin},200,200)`),hourHand.setAttribute("transform",`rotate(${angleHour},200,200)`),secHand.setAttribute("transform",`rotate(${angleSecond},200,200)`)}(d);if(document.getElementById("day")){dayText.innerHTML=weekdays[d.getDay()]}if(document.getElementById("date")){dateText.innerHTML=d.getDate()}}crown.addEventListener("click",(async()=>{if(crownOut=!crownOut,!crownOut)return await getUTC(),void crown.setAttribute("transform","translate(0 0)");crown.setAttribute("transform","translate(10 0)")})),async function(){getUTC().catch(console.error),getWeather().catch(console.error),setInterval(actual,200),setInterval(getWeather,15e3)}();
